### ISSUE TITLE
Cannot insert person from staff form, error on password 

### ISSUE THREAD

**Issue by ouPietMan** [StephanSchroder/TheThreeMusketeers#24]
![image](https://user-images.githubusercontent.com/36989145/47802035-20067000-dd38-11e8-8b4d-87ff8e0a860f.png)

**Comment by NicoC97** [comment]
Hover over the textfield to show the tooltip: "Must contain alphabetical characters and at least one numerical value and at least one special character. Min 4 characters. Max 20 characters"

This is implemented as a security measure
